apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsq6fluxq6
  labels:
    app: pagesq6
spec:
  replicas: 5
  selector:
    matchLabels:
      app: pagesq6
  template:
    metadata:
      labels:
        app: pagesq6
    spec:
      containers:
        - name: myimagescontainer
          image: n01529156/devopsfinal
